### ISSUE TITLE
Something wrong in regressor matrix computation

### ISSUE THREAD

**Issue by Ommac** [Ommac/semiparametric-matlab#1]
@traversaro

ottengo delle predizioni sballate, nell'ordine di 1e+4

ho controllato il regressore, e anche lui ha valori massimi ~1e+4.

mi sembra di aver calcolato la matrice dei regressori nel modo giusto, non capisco cosa non va:

https://github.com/Ommac/semiparametric-matlab/blob/master/semiparametric_CADpar_script.m#L144

**Comment by traversaro** [comment]
Mi controlli se la funzione toMatlab funziona correttamente?

**Comment by Ommac** [comment]
@traversaro Ho provato e mi pare che sia ok,

**Comment by traversaro** [comment]
Mismatch degree-radians?

**Comment by traversaro** [comment]
(setRobotState takes all angular values in radians)

**Comment by Ommac** [comment]
Thanks, that was one of the issues.

Now the predictions seem OK, but I get a sign mismatch and an offset between the known terms and the predictions:

![fx](https://cloud.githubusercontent.com/assets/6359405/8328008/6607bd0c-1a6d-11e5-9120-37f0c4091738.png)
![fy](https://cloud.githubusercontent.com/assets/6359405/8328009/660d0596-1a6d-11e5-90e4-521e2fb0db4c.png)
![fz](https://cloud.githubusercontent.com/assets/6359405/8328010/66162752-1a6d-11e5-83e6-9e19db6b6a3f.png)
![mux](https://cloud.githubusercontent.com/assets/6359405/8328011/661c654a-1a6d-11e5-879a-9a2f6025e6cf.png)
![muy](https://cloud.githubusercontent.com/assets/6359405/8328012/6620f308-1a6d-11e5-9948-8a010906d1a0.png)
![muz](https://cloud.githubusercontent.com/assets/6359405/8328013/66277de0-1a6d-11e5-865b-2c99784783d6.png)

**Comment by traversaro** [comment]
With the code in the repo? Can  you send me (even in private) the dataset so that I can try to debug on my machine?

**Comment by traversaro** [comment]
There was a bug in the example by the way, the gravity had the wrong sign : https://github.com/robotology-playground/idyntree/commit/80de8e9e4c7f9f1a2506693af7be2371d1ff13b3 .

**Comment by Ommac** [comment]
Code here: https://github.com/Ommac/semiparametric-matlab/commit/b4409498a2ea42af4a99979bc93247b8c17d689d

I'll send you the data in pvt.

**Comment by Ommac** [comment]
Note: The issue still happens by swapping the gravity sign.
